name: Check Lockfile

# Trigger on pull requests and pushes to main or any branch
on:
  pull_request:
    branches:
      - main
      - '**'
  push:
    branches:
      - main
      - '**'

jobs:
  check-lockfile:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3️⃣ Install dependencies using npm ci
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Verify lockfile is in sync
      - name: Check lockfile consistency
        run: |
          git diff --exit-code package-lock.json
        shell: bash
